version: '3.4'
services: 
  golang:
    image: golang
    volumes:
      - ./:/go/src/app
      - ./.infra/golang/pkg:/go/pkg/mod/cache
    working_dir: /go/src/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./.infra/mongodb/data:/data/db
  app:
    build:
      context: ./.docker/app/
      dockerfile: Dockerfile
    volumes:
      - ./main:/supermarket
      - ./.env:/.env
    ports:
      - 3000:3000
    depends_on:
      - mongo